# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-bsp/*/*.bb \
            ${LAYERDIR}/recipes-kernel/*/*.bbappend"

BBFILES += "${@bb.utils.contains_any('BBFILE_COLLECTIONS', 'meta-toradex-demos', \
           '${LAYERDIR}/recipes-images/images/tdx-reference-multimedia-image.bbappend', '', d)}"

BBFILE_COLLECTIONS += "meta-vc-mipi-dev"
BBFILE_PATTERN_meta-vc-mipi-dev = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-vc-mipi-dev = "6"

LAYERDEPENDS_meta-vc-mipi-dev = "core"
LAYERSERIES_COMPAT_meta-vc-mipi-dev = "kirkstone scarthgap"